version: '3'

services:
  langchain-serve:
    build:
      context: . 
      target: langchain-serve-img
    ports:
      - '5001:8080'
  pdf-gpt:
    build:
      context: . 
      target: pdf-gpt-img
    ports:
      - '5002:7860'